### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by rishabhSharmaOfficial** [rishabhSharmaOfficial/wheel#14]

**Comment by rishabhSharmaOfficial** [comment]
Deployed at: 
https://rishabh-neeto-ui.herokuapp.com/

Email: oliver@example.com
Password: welcome

**Comment by yedhink** [comment]
- [x] Go through the Slack thread.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/31244999/193042926-7fd8ac18-3bb3-4f13-8e35-79122ccd3ce4.png">

- [x] Contacts should be before settings. Settings always at the end.
<img width="56" alt="image" src="https://user-images.githubusercontent.com/31244999/193043168-d870a74a-80ba-4c91-a0cc-3ae5c40398e6.png">

Verify your UI thoroughly. Once you've made the changes lemme know over here once again.

**Comment by yedhink** [comment]
@rishabhSharmaOfficial

**Comment by rishabhSharmaOfficial** [comment]
I have made the changes requested along with some other minor UI changes. ( you can access using the same deploy link and credentials as before ).

**Comment by rishabhSharmaOfficial** [comment]
@yedhink

**Comment by yedhink** [comment]
@rishabhSharmaOfficial _a

Please go through https://handbook.neetokb.com/articles/git-and-github-essentials#self-review-process very thoroughly. These issues should've been caught in your self-review.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/31244999/193254502-f6205fab-2e34-42f5-a156-d7ca24959a86.png">

Only assign this issue back to me once you've verified all necessary changes from UI.

**Comment by rishabhSharmaOfficial** [comment]
I have fixed the problem pointed out. I somehow changed the placeholder and missed the requirement warning coupled with it. Also, the UI is not having any problems with it anymore. Can you point out anything else I might be missing from my side?

**Comment by yedhink** [comment]
@rishabhSharmaOfficial You can mark this task as completed and continue with the next task.
